version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - wget https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz
      - tar -xzf amazon-corretto-11-x64-linux-jdk.tar.gz
      - mv amazon-corretto-11.* amazon-corretto-11
      - export JAVA_HOME=$(pwd)/amazon-corretto-11
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - echo Installing JMeter...
      - wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
      - tar -xvzf apache-jmeter-5.6.3.tgz
      - export PATH=$(pwd)/apache-jmeter-5.6.3/bin:$PATH
      - jmeter -v
      - cd $(pwd)/apache-jmeter-5.6.3/lib && wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
      - cd ext && wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
      - cd .. && java -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all-except  jmeter-plugins-perfmon,jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583
      - cd ..
      - cd ..


  build:
    commands:
      - echo Running JMeter test...
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - jmeter -n -t TestPlans/NetBacksnew.jmx  -l results_${TIMESTAMP}.jtl

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - 'results_${TIMESTAMP}.jtl'


    
